{% set name = "datajudge" %}
{% set version = "1.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/datajudge-{{ version }}.tar.gz
  sha256: bf5cf54be6c2ac68c5b4f1b3637c5d772b3b101cf74c231793c77a19ce34b958

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - sqlalchemy >=1.4
    - scipy
  run:
    - python >={{ python_min }}
    - sqlalchemy >=1.4
    - scipy
    - colorama
    - pytest
test:
  imports:
    - datajudge
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/datajudge/
  summary: Datajudge allows to assess whether data from database complies with reference data.
  dev_url: https://github.com/quantco/datajudge
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kklein
    - ivergara
