{% set name = "datajudge" %}
{% set version = "1.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/datajudge-{{ version }}.tar.gz
  sha256: 1da23557b16f144c99655739a2c729b683cedea8e5751dfcf8eaaf2b401a786b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - sqlalchemy >=1.4
    - scipy
  run:
    - python >={{ python_min }}
    - sqlalchemy >=1.4
    - scipy
    - colorama
    - pytest
test:
  imports:
    - datajudge
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/datajudge/
  summary: Datajudge allows to assess whether data from database complies with reference data.
  dev_url: https://github.com/quantco/datajudge
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kklein
    - ivergara
