{% set name = "datajudge" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/datajudge-{{ version }}.tar.gz
  sha256: afc1357e7010746bc4139d966749b604f490a179c7621611b928e9a06ff77a18

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - flit-core >=3.2,<4
    - sqlalchemy >=1.4
    - scipy
  run:
    - python >=3.8
    - sqlalchemy >=1.4
    - scipy
test:
  imports:
    - datajudge
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/datajudge/
  summary: Datajudge allows to assess whether data from database complies with reference data.
  dev_url: https://github.com/quantco/datajudge
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kklein
    - ivergara
